### ISSUE TITLE
toDo

### ISSUE THREAD

**Issue by Nowosad** [skowronskij/prgdownloader#1]
- [ ] - podjęcie decyzji czy pakiet będzie po polsku (99% potencjalnych użytkowników) czy po angielsku, a następnie przerobienie dokumentacji na ten język
- [ ] - https://github.com/skowronskij/prg/blob/master/DESCRIPTION - Description tutaj musi się składać z co najmniej dwóch zdań
- [ ] - "Portable packages must use only ASCII characters in their R code, except perhaps in comments. Use \uxxxx escapes for other characters." Usunięcie polskich znaków w kodzie (chyba są tylko w errorach). Alternatywnie można zamienić polskie znaki na znaki w postacji \uxxxx, które będą potem poprawnie wyświetlane na różnych systemach operacyjnych (https://stackoverflow.com/questions/22223431/using-non-ascii-characters-inside-functions-for-packages)
- [ ] - uzupełnienie README
